# Generated by Django 5.1.4 on 2026-06-01 10:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'A user with that email already exists.'}, max_length=254, unique=True, verbose_name='email'),
        ),
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('code', models.CharField(max_length=6, verbose_name='verification code')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('is_used', models.BooleanField(default=False, verbose_name='used')),
            ],
            options={
                'verbose_name': 'email verification',
                'verbose_name_plural': 'email verifications',
                'db_table': 'email_verification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', '-created_at'], name='idx_email_created')],
            },
        ),
    ]
