# Generated by Django 5.1.4 on 2026-06-03 13:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_tag_task_tasktag_task_tags_task_idx_task_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(default='todo', max_length=50, verbose_name='status'),
        ),
        migrations.CreateModel(
            name='BoardColumn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('slug', models.CharField(max_length=50, verbose_name='slug')),
                ('position', models.IntegerField(default=0, verbose_name='position')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_columns', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'verbose_name': 'board column',
                'verbose_name_plural': 'board columns',
                'db_table': 'board_columns',
                'ordering': ['position'],
                'constraints': [models.UniqueConstraint(fields=('created_by', 'slug'), name='unique_column_slug_per_user')],
            },
        ),
    ]
