# Generated by Django 5.1.4 on 2026-06-03 13:15

from django.db import migrations

DEFAULT_COLUMNS = [
    {"slug": "todo", "name": "待办", "position": 0},
    {"slug": "in_progress", "name": "进行中", "position": 1},
    {"slug": "done", "name": "已完成", "position": 2},
]


def create_default_columns(apps, schema_editor):
    User = apps.get_model("api", "User")
    BoardColumn = apps.get_model("api", "BoardColumn")
    for user in User.objects.all():
        if not BoardColumn.objects.filter(created_by=user).exists():
            for col in DEFAULT_COLUMNS:
                BoardColumn.objects.create(
                    name=col["name"],
                    slug=col["slug"],
                    position=col["position"],
                    created_by=user,
                )


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_task_status_boardcolumn"),
    ]

    operations = [
        migrations.RunPython(create_default_columns, migrations.RunPython.noop),
    ]
