# Generated by Django 5.1.4 on 2026-06-06 17:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_add_default_columns'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='timestamp')),
                ('method', models.CharField(max_length=10, verbose_name='method')),
                ('path', models.CharField(max_length=500, verbose_name='path')),
                ('status_code', models.IntegerField(verbose_name='status code')),
                ('message', models.TextField(blank=True, default='', verbose_name='message')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'error log',
                'verbose_name_plural': 'error logs',
                'db_table': 'error_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='idx_error_timestamp')],
            },
        ),
    ]
