# Generated by Django 5.1.4 on 2026-06-07 15:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_errorlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10, verbose_name='role')),
                ('content', models.TextField(verbose_name='content')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'chat message',
                'verbose_name_plural': 'chat messages',
                'db_table': 'chat_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tool_name', models.CharField(max_length=50, verbose_name='tool name')),
                ('tool_args', models.JSONField(verbose_name='tool args')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('executed', 'Executed'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('undone', 'Undone')], default='pending', max_length=10, verbose_name='status')),
                ('result', models.JSONField(blank=True, null=True, verbose_name='result')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='api.chatmessage', verbose_name='message')),
            ],
            options={
                'verbose_name': 'AI action',
                'verbose_name_plural': 'AI actions',
                'db_table': 'ai_actions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('count', models.IntegerField(default=0, verbose_name='count')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_daily_usages', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'daily usage',
                'verbose_name_plural': 'daily usages',
                'db_table': 'daily_usages',
            },
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['user', '-created_at'], name='idx_chat_user_created'),
        ),
        migrations.AddIndex(
            model_name='aiaction',
            index=models.Index(fields=['message'], name='idx_ai_action_message'),
        ),
        migrations.AddConstraint(
            model_name='dailyusage',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='uq_daily_usage_user_date'),
        ),
    ]
